version: '3.5'
services:
    # evalite-refsys-nginx:
    #     build: ./docker/images/nginx
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #         # - ./application:/var/www/html
    #         # - ./logs:/var/log/nginx
    #         # - ./docker/images/certbot/conf:/etc/letsencrypt
    #         # - ./docker/images/certbot/www:/var/www/certbot
    #     restart: unless-stopped
    #     links:
    #         - evalite-refsys-app-nuxt
    #     networks:
    #         - evalite-refsys-network-spa

    evalite-refsys-app-nuxt:
        build: ./
        ports:
            - "3001:80"
        # working_dir: /application
        networks:
            - evalite-refsys-network-spa
        # volumes:
        #     - ./application:/var/www/html
        restart: unless-stopped

networks:
    evalite-refsys-network-spa:
        driver: bridge
