export const userDomain = {
  firstName: '',
  secondName: '',
  thirdName: '',
  gender: '',
  birthday: '',
  employmentType: '',
  email: '',
  phone: '',
  inviteCode: '',
  individualCode: '',
  promoCode: '',
  role: '',
  uuid: '',
};
