<template lang="pug">
.verifications
  AppFilterTable.verifications--filter(
    @apply="applyFilter",
    @reset="resetFilter"
  )
    AppPickerDate.verifications--filter__field(
      :range="true",
      :value="filterDate",
      @ok="setFilterDate"
    )
    AppTextField.verifications--filter__field(
      v-model="filterEmail",
      label="Email"
    )
    AppTextField.verifications--filter__field(
      v-model="filterName",
      label="ФИО"
    )

  AppTable(
    :headers="headers",
    :items="items",
    :loading="loading",
    :loading-text="'Данные загружаются'",
    :page="page",
    :lastPage="lastPage",
    :itemsPerPage="itemsPerPage",
    :itemsLength="itemsLength",
    @click:row="openVerificationsDetailDialog",
    @update:page="updatePage",
    @update:itemsPerPage="updateItemsPerPage"
  )

  VerificationsDetail(
    :user="verificationsDetail",
    :edited="verificationsDetailEdited",
    :dialog="verificationsDetailDialog",
    :loading="verificationsDetailLoading",
    :saveLoading="verificationsDetailLoadingSave",
    :approveLoading="verificationsDetailLoadingApprove",
    @close="closeVerificationsDetailDialog",
    @approve="approveVerificationsDetail",
    @save="saveVerificationsDetail",
    @update:avatar="updateAvatar",
    @update:second_name="updateSecondName",
    @update:first_name="updateFirstName",
    @update:third_name="updateThirdName",
    @update:gender="updateGender",
    @update:birthday="updateBirthday",
    @update:email="updateEmail",
    @update:phone="updatePhone",
    @update:pass_full_name="updateFullNamePass",
    @update:pass_series="updateSeriesPass",
    @update:pass_number="updateNumberPass",
    @update:pass_issue_date="updateIssueDatePass",
    @update:pass_registration_address="updateRegistrationAddressPass",
    @update:pass_issue_by="updateIssueByPass",
    @update:pass_department_code="updateDepartmentCodePass",
    @update:pass_main_spread="updateMainSpreadPass",
    @update:pass_registration_spread="updateRegistrationSpreadPass",
    @update:pass_verification_spread="updateVerificationSpreadPass",
    @update:full_name_se="updateFullNameSe",
    @update:transaction_account_se="updateTransactionAccountSe",
    @update:inn_se="updateInnSe",
    @update:swift_se="updateSwiftSe",
    @update:mailing_address_se="updateMailingAddressSe",
    @update:bank_se="updateBankSe",
    @update:bic_se="updateBicSe",
    @update:correspondent_account_se="updateCorrespondentAccountSe",
    @update:bank_inn_se="updateBankInnSe",
    @update:bank_kpp_se="updateBankKppSe",
    @update:confirm_doc_se="updateConfirmDocSe",
    @update:full_name_ie="updateFullNameIE",
    @update:organization_legal_address_ie="updateOrganizationLegalAddressIE",
    @update:inn_ie="updateInnIE",
    @update:ogrn_ie="updateOgrnIE",
    @update:transaction_account_ie="updateTransactionAccountIE",
    @update:bank_ie="updateBankIE",
    @update:bank_inn_ie="updateBankInnIE",
    @update:bank_bic_ie="updateBankBicIE",
    @update:bank_correspondent_account_ie="updateBankCorrespondentAccountIE",
    @update:bank_legal_address_ie="updateBankLegalAddressIE",
    @update:confirm_doc_ie="updateConfirmDocIE",
    @update:agency_contract="updateAgencyContract"
  )
</template>

<script src="./Verifications.js" />
<style lang="scss" src="./Verifications.scss" />
